-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.4'
    hooks:
    -   id: autopep8
        args:
        - '-i'
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    -   id: autoflake